package main

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"sync"
	"time"

	"github.com/browserutils/kooky"
	_ "github.com/browserutils/kooky/browser/all"
)

// CookieMode defines how cookies are handled
type CookieMode string

const (
	CookieModeNone    CookieMode = "none"
	CookieModeManual  CookieMode = "manual"
	CookieModeBrowser CookieMode = "browser"
)

// CookieConfig represents the persistent cookie settings
type CookieConfig struct {
	Mode            CookieMode `json:"mode"`
	SelectedBrowser string     `json:"selected_browser"`
	ManualHeader    string     `json:"manual_header,omitempty"` // Used for persistent manual cookies if desired
}

type temporaryCookieState struct {
	mu            sync.RWMutex
	header        string
	cookies       []parsedCookie
	tempFile      string
	xhsSession    string    // Cache for Xiaohongshu session
	xhsCacheTime  time.Time // When the cache was last updated
	xhsExtracting bool

	domainBrowserData map[string]*BrowserExportData
}

type parsedCookie struct {
	Domain  string `json:"domain,omitempty"`
	Path    string `json:"path,omitempty"`
	Name    string `json:"name"`
	Value   string `json:"value"`
	Secure  bool   `json:"secure,omitempty"`
	Expires int64  `json:"expires,omitempty"`
}

type BrowserExportData struct {
	BrowserName string            `json:"browser"`
	UserAgent   string            `json:"user_agent"`
	WebSession  string            `json:"web_session,omitempty"`
	Cookies     []parsedCookie    `json:"cookies"`
	Headers     map[string]string `json:"headers,omitempty"`
	ExportTime  time.Time         `json:"-"`
}

// Global cookie state manager
type CookieManager struct {
	mu           sync.RWMutex
	config       CookieConfig
	state        temporaryCookieState
	extractionMu sync.Mutex
}

var manager = &CookieManager{
	config: CookieConfig{
		Mode: CookieModeNone,
	},
	state: temporaryCookieState{
		domainBrowserData: make(map[string]*BrowserExportData),
	},
}

var cookieNamePattern = regexp.MustCompile(`^[A-Za-z0-9!#$%&'*+\-.^_` + "`" + `|~]+$`)

// writeCookiesToNetscapeFile converts a cookie header string (e.g., "name1=value1; name2=value2")
// into Netscape cookie file format and writes to a temp file
// url parameter is used to determine the correct domain for the cookies
func writeCookiesToNetscapeFile(headerString string, url string) (string, error) {
	// Create temp file
	tmpFile, err := os.CreateTemp("", "ytdown-cookie-*.txt")
	if err != nil {
		return "", err
	}
	defer tmpFile.Close()

	// Write Netscape cookie file header
	tmpFile.WriteString("# Netscape HTTP Cookie File\n")
	tmpFile.WriteString("# This file is generated by YTDown\n\n")

	// Detect domain from URL
	domain := ".youtube.com" // Default
	if strings.Contains(url, "instagram.com") {
		domain = ".instagram.com"
	} else if strings.Contains(url, "twitter.com") || strings.Contains(url, "x.com") {
		domain = ".twitter.com"
	} else if strings.Contains(url, "tiktok.com") {
		domain = ".tiktok.com"
	} else if strings.Contains(url, "xiaohongshu.com") || strings.Contains(url, "xhslink.com") {
		domain = ".xiaohongshu.com"
	} else if strings.Contains(url, "pixiv.net") {
		domain = ".pixiv.net"
	} else if strings.Contains(url, "youtube.com") {
		domain = ".youtube.com"
	}

	LogDebug("[Cookie] Detected domain for Netscape file: %s (from URL: %s)", domain, url)

	// Parse cookie string: "name1=value1; name2=value2; ..."
	pairs := strings.Split(headerString, ";")
	for _, pair := range pairs {
		pair = strings.TrimSpace(pair)
		if pair == "" {
			continue
		}

		// Split by first = to get name and value
		idx := strings.Index(pair, "=")
		if idx < 0 {
			continue
		}

		name := strings.TrimSpace(pair[:idx])
		value := strings.TrimSpace(pair[idx+1:])

		// Skip if name is empty
		if name == "" {
			continue
		}

		// Write in Netscape format: domain, flag, path, secure, expiration, name, value
		line := fmt.Sprintf("%s\tTRUE\t/\tTRUE\t2147483647\t%s\t%s\n", domain, name, value)
		tmpFile.WriteString(line)
	}

	return tmpFile.Name(), nil
}

// GetConfigDir returns the path to the app's config directory
func GetConfigDir() string {
	configDir, err := os.UserConfigDir()
	if err != nil {
		return ""
	}
	dir := filepath.Join(configDir, "YTDown")
	_ = os.MkdirAll(dir, 0755)
	return dir
}

// LoadConfig loads the cookie configuration from disk
func (m *CookieManager) LoadConfig() {
	m.mu.Lock()
	defer m.mu.Unlock()

	dir := GetConfigDir()
	if dir == "" {
		return
	}

	path := filepath.Join(dir, "cookies_settings.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}

	_ = json.Unmarshal(data, &m.config)

	// If mode is manual, we don't restore the header from disk for security/freshness
	// unless we specifically want to. The user said manual should be cleared on exit,
	// so we keep it empty in memory on startup.
	if m.config.Mode == CookieModeManual {
		m.config.ManualHeader = ""
	}
}

// SaveConfig saves the cookie configuration to disk
func (m *CookieManager) SaveConfig() {
	m.mu.RLock()
	defer m.mu.RUnlock()

	dir := GetConfigDir()
	if dir == "" {
		return
	}

	path := filepath.Join(dir, "cookies_settings.json")

	// Prepare config for saving (clear manual header as it's session-only)
	saveCfg := m.config
	if saveCfg.Mode == CookieModeManual {
		saveCfg.ManualHeader = ""
	}

	data, _ := json.MarshalIndent(saveCfg, "", "  ")
	_ = os.WriteFile(path, data, 0644)
}

// GetCookieArgs returns the command line arguments for cookies
func (m *CookieManager) GetCookieArgs(ctx context.Context, tool string, url string) []string {
	m.mu.RLock()
	cfg := m.config
	m.mu.RUnlock()

	var args []string
	isXHS := IsXiaohongshu(url)

	switch cfg.Mode {
	case CookieModeBrowser:
		if cfg.SelectedBrowser != "" {
			data, err := m.GetBrowserData(ctx, cfg.SelectedBrowser, url)

			if err == nil && data != nil && len(data.Cookies) > 0 {
				tempFile, err := writeParsedCookiesToNetscapeFile(data.Cookies)
				if err == nil && tempFile != "" {
					args = append(args, "--cookies", tempFile)
				}
				if data.UserAgent != "" {
					switch tool {
					case "yt-dlp":
						args = append(args, "--user-agent", data.UserAgent)
					case "gallery-dl":
						args = append(args, "-o", "http.headers.User-Agent="+data.UserAgent)
					}
				}

				if isXHS && tool == "yt-dlp" {
					if data.WebSession != "" {
						args = append(args, "--add-headers", "Cookie: web_session="+data.WebSession)
						fmt.Printf("[Cookie] ✅ Found web_session via kooky: %s\n", data.WebSession)
					} else {
						LogWarning("[Cookie] Could NOT find web_session in %s cookies.", cfg.SelectedBrowser)
						fmt.Printf("[Cookie] ❌ Failed to find web_session in %s. Please check login status.\n", cfg.SelectedBrowser)
					}
				}
			} else {
				// Fallback to yt-dlp native extraction
				if isXHS && tool == "yt-dlp" {
					fmt.Printf("[Cookie] 🔍 Detecting Xiaohongshu, trying to extract web_session from %s via yt-dlp...\n", cfg.SelectedBrowser)
					session := m.extractWebSessionFromBrowser(ctx, cfg.SelectedBrowser, url)
					if session != "" {
						args = append(args, "--add-headers", "Cookie: web_session="+session)
						LogInfo("[Cookie] Successfully extracted web_session from %s: %s", cfg.SelectedBrowser, session)
						fmt.Printf("[Cookie] ✅ Found web_session via yt-dlp: %s\n", session)
						args = append(args, "--cookies-from-browser", cfg.SelectedBrowser)
					} else {
						LogWarning("[Cookie] Could NOT find web_session in %s cookies. Make sure you are logged in to Xiaohongshu.", cfg.SelectedBrowser)
						fmt.Printf("[Cookie] ❌ Failed to find web_session in %s. Please check login status.\n", cfg.SelectedBrowser)
						args = append(args, "--cookies-from-browser", cfg.SelectedBrowser)
					}
				} else {
					args = append(args, "--cookies-from-browser", cfg.SelectedBrowser)
				}
			}
		}
	case CookieModeManual:
		m.state.mu.RLock()
		header := m.state.header
		tempFile := m.state.tempFile
		m.state.mu.RUnlock()

		if header != "" && tempFile != "" {
			// Dùng lại file đã tạo bởi setManualCookie — không tạo temp mới
			args = append(args, "--cookies", tempFile)
			LogInfo("[Cookie] Reusing existing cookie file: %s", tempFile)
		} else if header != "" {
			// Fallback nếu tempFile chưa có (trường hợp hiếm)
			LogWarning("[Cookie] No temp cookie file found, falling back to header")
			switch tool {
			case "gallery-dl":
				args = append(args, "-o", "http.headers.Cookie="+header)
			case "yt-dlp":
				args = append(args, "--add-headers", "Cookie: "+header)
			}
		}

		// Cảnh báo nếu XHS mà không có web_session trong cookie
		if isXHS && tool == "yt-dlp" && header != "" && !strings.Contains(header, "web_session=") {
			LogWarning("[Cookie] Xiaohongshu detected but web_session missing from manual cookie")
		}

	}
	return args
}

func (m *CookieManager) GetBrowserData(ctx context.Context, browser string, targetURL string) (*BrowserExportData, error) {
	parsed, _ := url.Parse(targetURL)
	targetHost := ""
	if parsed != nil {
		targetHost = parsed.Hostname()
	}

	baseDomain := ""
	if targetHost != "" {
		parts := strings.Split(targetHost, ".")
		if len(parts) >= 2 {
			baseDomain = parts[len(parts)-2] + "." + parts[len(parts)-1]
		}
	}
	if baseDomain == "" {
		baseDomain = "unknown"
	}

	cacheKey := browser + "|" + baseDomain

	m.state.mu.RLock()
	if m.state.domainBrowserData == nil {
		m.state.mu.RUnlock()
		m.state.mu.Lock()
		m.state.domainBrowserData = make(map[string]*BrowserExportData)
		m.state.mu.Unlock()
		m.state.mu.RLock()
	}
	data := m.state.domainBrowserData[cacheKey]
	m.state.mu.RUnlock()

	if data != nil && time.Since(data.ExportTime) < 5*time.Minute {
		return data, nil
	}

	m.extractionMu.Lock()
	defer m.extractionMu.Unlock()

	m.state.mu.RLock()
	data = m.state.domainBrowserData[cacheKey]
	m.state.mu.RUnlock()

	if data != nil && time.Since(data.ExportTime) < 5*time.Minute {
		return data, nil
	}

	newData, err := m.ExtractBrowserDataForDomain(ctx, browser, targetHost)
	if err != nil {
		return nil, err
	}

	m.state.mu.Lock()
	m.state.domainBrowserData[cacheKey] = newData
	m.state.mu.Unlock()

	return newData, nil
}

func (m *CookieManager) ExtractBrowserDataForDomain(ctx context.Context, browser string, targetHost string) (*BrowserExportData, error) {
	if runtime.GOOS == "linux" {
		return m.extractBrowserDataViaYTDLP(ctx, browser, targetHost)
	}

	stores := kooky.FindAllCookieStores(ctx)

	var allCookies []parsedCookie
	var xhsSession string

	var relevantDomains []string
	if targetHost != "" {
		parts := strings.Split(targetHost, ".")
		if len(parts) >= 2 {
			base := parts[len(parts)-2] + "." + parts[len(parts)-1]
			relevantDomains = append(relevantDomains, base)
		}
	}
	// Special domain logic
	if strings.Contains(targetHost, "youtube.com") || strings.Contains(targetHost, "youtu.be") {
		relevantDomains = []string{"youtube.com"} // ONLY youtube.com, removed google.com per user request
	} else if strings.Contains(targetHost, "xiaohongshu.com") || strings.Contains(targetHost, "xhslink.com") {
		relevantDomains = []string{"xiaohongshu.com", "xhslink.com"}
	}

	var filters []kooky.Filter
	filters = append(filters, kooky.Valid)

	cookieMap := make(map[string]parsedCookie)

	getBaseDomain := func(d string) string {
		d = strings.TrimPrefix(d, ".")
		parts := strings.Split(d, ".")
		if len(parts) >= 2 {
			return parts[len(parts)-2] + "." + parts[len(parts)-1]
		}
		return d
	}

	for _, store := range stores {
		if strings.EqualFold(store.Browser(), browser) {
			cookies := store.TraverseCookies(filters...).Collect(ctx)
			for _, c := range cookies {
				// domain filter
				if len(relevantDomains) > 0 {
					matched := false
					for _, rd := range relevantDomains {
						if strings.HasSuffix(c.Domain, rd) {
							matched = true
							break
						}
					}
					if !matched {
						continue
					}
				}

				// skip excessively large cookies (YouTube max header is 8KB)
				if len(c.Name)+len(c.Value) > 1000 {
					continue
				}

				baseDom := getBaseDomain(c.Domain)
				key := fmt.Sprintf("%s|%s", baseDom, c.Name) // Strict deduplication by base domain and name

				// Prefer cookies with actual values if a duplicate exists
				if existing, exists := cookieMap[key]; exists {
					if c.Value != "" && existing.Value == "" {
						cookieMap[key] = parsedCookie{
							Domain:  c.Domain,
							Path:    c.Path,
							Name:    c.Name,
							Value:   c.Value,
							Secure:  c.Secure,
							Expires: c.Expires.Unix(),
						}
					}
				} else {
					cookieMap[key] = parsedCookie{
						Domain:  c.Domain,
						Path:    c.Path,
						Name:    c.Name,
						Value:   c.Value,
						Secure:  c.Secure,
						Expires: c.Expires.Unix(),
					}
				}

				if (strings.Contains(c.Domain, "xiaohongshu.com") || strings.Contains(c.Domain, "xhslink.com")) && c.Name == "web_session" {
					xhsSession = c.Value
				}
			}
		}
	}

	for _, c := range cookieMap {
		allCookies = append(allCookies, c)
	}

	userAgent := GetUserAgent(browser)

	data := &BrowserExportData{
		BrowserName: browser,
		UserAgent:   userAgent,
		WebSession:  xhsSession,
		Cookies:     allCookies,
		Headers:     make(map[string]string),
		ExportTime:  time.Now(),
	}

	if xhsSession != "" {
		data.Headers["Cookie"] = "web_session=" + xhsSession
	}

	return data, nil
}

func (m *CookieManager) exportBrowserDataToJSON(data *BrowserExportData) {
	dir := GetConfigDir()
	if dir == "" {
		return
	}
	path := filepath.Join(dir, "browser_export.json")
	bytes, _ := json.MarshalIndent(data, "", "  ")
	_ = os.WriteFile(path, bytes, 0644)
}

func writeParsedCookiesToNetscapeFile(cookies []parsedCookie) (string, error) {
	dir := filepath.Join(os.TempDir(), "ytdown")
	os.MkdirAll(dir, 0755)

	tmpFile, err := os.CreateTemp(dir, "cookies-*.txt")
	if err != nil {
		return "", err
	}
	path := tmpFile.Name()
	defer tmpFile.Close()

	tmpFile.WriteString("# Netscape HTTP Cookie File\n")

	LogInfo("[Cookie] Writing %d cookies to %s", len(cookies), path)
	var cookieNames []string

	for _, c := range cookies {
		domain := c.Domain
		if domain == "" {
			continue
		}

		if !strings.HasPrefix(domain, ".") {
			domain = "." + domain
		}
		domainSpecified := "TRUE"

		cPath := c.Path
		if cPath == "" {
			cPath = "/"
		}
		secure := "FALSE"
		if c.Secure {
			secure = "TRUE"
		}
		expires := c.Expires
		if expires <= 0 {
			expires = 2147483647
		}

		name := strings.ReplaceAll(c.Name, "\n", "")
		name = strings.ReplaceAll(name, "\r", "")
		name = strings.ReplaceAll(name, "\t", "%09")

		value := strings.ReplaceAll(c.Value, "\n", "")
		value = strings.ReplaceAll(value, "\r", "")
		value = strings.ReplaceAll(value, "\t", "%09")

		line := fmt.Sprintf("%s\t%s\t%s\t%s\t%d\t%s\t%s\n", domain, domainSpecified, cPath, secure, expires, name, value)
		tmpFile.WriteString(line)

		cookieNames = append(cookieNames, name)
	}

	LogInfo("[Cookie] Included cookies: %s", strings.Join(cookieNames, ", "))
	return path, nil
}

var xhsDomains = []string{
	"xiaohongshu.com",
	"xhslink.com",
	"redbookchina.com",
}

// IsXiaohongshu checks if the URL belongs to Xiaohongshu
func IsXiaohongshu(url string) bool {
	lower := strings.ToLower(url)
	for _, domain := range xhsDomains {
		if strings.Contains(lower, domain) {
			return true
		}
	}
	return false
}

// extractWebSessionFromBrowser uses yt-dlp to extract the web_session cookie from a browser
func (m *CookieManager) extractWebSessionFromBrowser(ctx context.Context, browser string, url string) string {
	// 1. Check Cache first (Valid for 5 minutes)
	m.state.mu.RLock()
	if m.state.xhsSession != "" && time.Since(m.state.xhsCacheTime) < 5*time.Minute {
		session := m.state.xhsSession
		m.state.mu.RUnlock()
		fmt.Printf("[Cookie] ⚡ Using CACHED web_session: %s\n", session)
		return session
	}
	isExtracting := m.state.xhsExtracting
	m.state.mu.RUnlock()

	if isExtracting {
		// Chờ tối đa 15s để goroutine kia xong
		for i := 0; i < 30; i++ {
			time.Sleep(500 * time.Millisecond)
			m.state.mu.RLock()
			session := m.state.xhsSession
			done := !m.state.xhsExtracting
			m.state.mu.RUnlock()
			if session != "" || done {
				return session
			}
		}
		return ""
	}

	m.state.mu.Lock()
	m.state.xhsExtracting = true
	m.state.mu.Unlock()
	defer func() {
		m.state.mu.Lock()
		m.state.xhsExtracting = false
		m.state.mu.Unlock()
	}()

	ytdlp := getResourcePath("yt-dlp")
	if ytdlp == "" {
		return ""
	}

	m.mu.RLock()
	selectedBrowser := m.config.SelectedBrowser
	m.mu.RUnlock()

	// Resolve URL first
	resolvedURL := ResolveShortURL(url, GetUserAgent(selectedBrowser))

	// Use the base domain for cookie extraction for Xiaohongshu
	extractionURL := resolvedURL
	if IsXiaohongshu(resolvedURL) {
		extractionURL = "https://www.xiaohongshu.com/"
	}

	// Create a temporary file to store cookies
	tempDir, err := os.MkdirTemp("", "ytdown-xhs-*")
	if err != nil {
		return ""
	}
	defer os.RemoveAll(tempDir)
	tempCookieFile := filepath.Join(tempDir, "cookies.txt")

	checkCtx, cancel := context.WithTimeout(ctx, 15*time.Second)
	defer cancel()

	fmt.Printf("[Cookie] 🛠️  Exporting cookies from %s to temporary file...\n", browser)
	// Using --cookies to export to a file instead of --print-cookies
	cmd := exec.CommandContext(checkCtx, ytdlp, "--cookies-from-browser", browser, "--cookies", tempCookieFile, "--no-warnings", "--no-playlist", extractionURL)
	_, err = cmd.CombinedOutput()

	if err != nil {
		fmt.Printf("[Cookie] ℹ️  yt-dlp export status: %v\n", err)
	}

	// Read the temporary cookie file
	data, err := os.ReadFile(tempCookieFile)
	if err != nil {
		fmt.Printf("[Cookie] ❌ Could not read temporary cookie file: %v\n", err)
		return ""
	}

	outputStr := string(data)
	var session string

	// Parse Netscape cookie format in the file
	lines := strings.Split(outputStr, "\n")
	for _, line := range lines {
		if strings.Contains(line, "web_session") {
			parts := strings.Fields(line)
			// Netscape format: domain, flag, path, secure, expiration, name, value
			if len(parts) >= 7 && (parts[5] == "web_session" || strings.Contains(parts[5], "web_session")) {
				session = parts[6]
				break
			}
		}
	}

	// Fallback regex search in the file content
	if session == "" {
		re := regexp.MustCompile(`web_session\s+([\w\-%.]+)`)
		matches := re.FindStringSubmatch(outputStr)
		if len(matches) > 1 {
			session = matches[1]
		}
	}

	if session != "" {
		m.state.mu.Lock()
		m.state.xhsSession = session
		m.state.xhsCacheTime = time.Now()
		m.state.mu.Unlock()
		fmt.Printf("[Cookie] ✅ web_session extracted: %s\n", session)
	}

	return session
}

func setManualCookie(raw string) error {
	// Try parsing as YouTube first to see if we should give a warning,
	// but don't fail if it's not YouTube.
	cookies, err := parseCookieInput(raw, false)
	if err != nil {
		return err
	}

	// For the temporary file, we'll use a set of common domains to make it "universal"
	commonDomains := []string{
		".youtube.com",
		".facebook.com",
		".instagram.com",
		".tiktok.com",
		".twitter.com",
		".x.com",
		".vimeo.com",
		".bilibili.com",
		".douyin.com",
		".reddit.com",
		".twitch.tv",
		".google.com",
		".pinterest.com",
		".linkedin.com",
		".xiaohongshu.com",
		".xhslink.com",
	}

	tempFile, err := writeMultiDomainCookieFile(cookies, commonDomains)
	if err != nil {
		return err
	}

	manager.state.mu.Lock()
	if manager.state.tempFile != "" && manager.state.tempFile != tempFile {
		_ = os.RemoveAll(filepath.Dir(manager.state.tempFile))
	}

	pairs := make([]string, 0, len(cookies))
	for _, cookie := range cookies {
		pairs = append(pairs, cookie.Name+"="+cookie.Value)
	}

	manager.state.header = strings.Join(pairs, "; ")
	manager.state.cookies = cookies
	manager.state.tempFile = tempFile
	manager.state.mu.Unlock()

	manager.mu.Lock()
	manager.config.Mode = CookieModeManual
	manager.mu.Unlock()
	manager.SaveConfig()

	return nil
}

func writeMultiDomainCookieFile(cookies []parsedCookie, domains []string) (string, error) {
	dir, err := os.MkdirTemp("", "ytdown-cookie-*")
	if err != nil {
		return "", fmt.Errorf("failed to prepare temporary cookie storage: %w", err)
	}

	path := filepath.Join(dir, "cookies.txt")
	file, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0600)
	if err != nil {
		_ = os.RemoveAll(dir)
		return "", fmt.Errorf("failed to create temporary cookie file: %w", err)
	}
	defer file.Close()

	if _, err := file.WriteString("# Netscape HTTP Cookie File\n"); err != nil {
		_ = os.RemoveAll(dir)
		return "", fmt.Errorf("failed to write temporary cookie file: %w", err)
	}

	for _, domain := range domains {
		for _, cookie := range cookies {
			line := fmt.Sprintf("%s\tTRUE\t/\tTRUE\t2147483647\t%s\t%s\n", domain, cookie.Name, cookie.Value)
			if _, err := file.WriteString(line); err != nil {
				_ = os.RemoveAll(dir)
				return "", fmt.Errorf("failed to write temporary cookie file: %w", err)
			}
		}
	}

	return path, nil
}

// Compatibility functions for existing code

func setTemporaryYouTubeCookie(raw string) error {
	return setManualCookie(raw)
}

func setGalleryCookie(raw string) error {
	// Re-using the same logic as YouTube for unified cookies
	return setTemporaryYouTubeCookie(raw)
}

func getGalleryCookieHeader() string {
	manager.state.mu.RLock()
	defer manager.state.mu.RUnlock()
	return manager.state.header
}

func hasGalleryCookie() bool {
	manager.mu.RLock()
	mode := manager.config.Mode
	manager.mu.RUnlock()

	if mode == CookieModeBrowser {
		return true
	}

	manager.state.mu.RLock()
	defer manager.state.mu.RUnlock()
	return manager.state.header != ""
}

func hasTemporaryCookie() bool {
	manager.mu.RLock()
	mode := manager.config.Mode
	manager.mu.RUnlock()

	if mode == CookieModeBrowser {
		return true
	}

	manager.state.mu.RLock()
	defer manager.state.mu.RUnlock()
	return manager.state.tempFile != ""
}

func getTemporaryCookieFile() string {
	manager.state.mu.RLock()
	defer manager.state.mu.RUnlock()
	return manager.state.tempFile
}

func clearManualCookie() {
	manager.state.mu.Lock()
	if manager.state.tempFile != "" {
		_ = os.RemoveAll(filepath.Dir(manager.state.tempFile))
	}
	manager.state.header = ""
	manager.state.tempFile = ""
	manager.state.cookies = nil
	manager.state.xhsSession = ""
	manager.state.xhsCacheTime = time.Time{}
	manager.state.domainBrowserData = nil
	manager.state.mu.Unlock()
	ClearUserAgentCache()

	manager.mu.Lock()
	manager.config.Mode = CookieModeNone
	manager.mu.Unlock()
	manager.SaveConfig()
}

func clearTemporaryYouTubeCookie() {
	clearManualCookie()
}

// Utility functions kept from original

func parseCookieInput(raw string, isYouTube bool) ([]parsedCookie, error) {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return nil, fmt.Errorf("cookie input is empty")
	}

	if extracted := extractCookieHeader(trimmed); extracted != "" {
		trimmed = extracted
	}

	parts := strings.Split(trimmed, ";")
	cookies := make([]parsedCookie, 0, len(parts))
	seen := make(map[string]bool)

	for _, part := range parts {
		token := strings.TrimSpace(strings.ReplaceAll(part, "\n", " "))
		token = strings.TrimSpace(strings.ReplaceAll(token, "\r", " "))
		if token == "" {
			continue
		}

		name, value, ok := strings.Cut(token, "=")
		if !ok {
			continue
		}

		name = strings.TrimSpace(name)
		value = strings.TrimSpace(value)
		if name == "" || value == "" {
			continue
		}
		if !cookieNamePattern.MatchString(name) {
			continue
		}

		if seen[name] {
			for i := range cookies {
				if cookies[i].Name == name {
					cookies[i].Value = value
					break
				}
			}
			continue
		}

		seen[name] = true
		cookies = append(cookies, parsedCookie{
			Name:  name,
			Value: value,
		})
	}

	if len(cookies) == 0 {
		return nil, fmt.Errorf("no valid cookie pairs found")
	}

	if isYouTube && !hasUsefulYouTubeAuthCookie(cookies) {
		return nil, fmt.Errorf("no usable YouTube authentication cookies found. Please copy a fresh YouTube Cookie header")
	}

	return cookies, nil
}

func extractCookieHeader(raw string) string {
	lines := strings.Split(raw, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(strings.ToLower(line), "cookie:") {
			return strings.TrimSpace(line[len("cookie:"):])
		}
	}
	return raw
}

func hasUsefulYouTubeAuthCookie(cookies []parsedCookie) bool {
	authNames := map[string]struct{}{
		"SAPISID":           {},
		"__Secure-1PSID":    {},
		"__Secure-3PSID":    {},
		"SID":               {},
		"SSID":              {},
		"HSID":              {},
		"LOGIN_INFO":        {},
		"__Secure-1PAPISID": {},
		"__Secure-3PAPISID": {},
	}

	for _, cookie := range cookies {
		if _, ok := authNames[cookie.Name]; ok {
			return true
		}
	}

	return false
}

func writeTemporaryCookieFile(cookies []parsedCookie, domain string) (string, error) {
	dir, err := os.MkdirTemp("", "ytdown-cookie-*")
	if err != nil {
		return "", fmt.Errorf("failed to prepare temporary cookie storage: %w", err)
	}

	path := filepath.Join(dir, "cookies.txt")
	file, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0600)
	if err != nil {
		_ = os.RemoveAll(dir)
		return "", fmt.Errorf("failed to create temporary cookie file: %w", err)
	}
	defer file.Close()

	if _, err := file.WriteString("# Netscape HTTP Cookie File\n"); err != nil {
		_ = os.RemoveAll(dir)
		return "", fmt.Errorf("failed to write temporary cookie file: %w", err)
	}

	for _, cookie := range cookies {
		d := domain
		if d == "" {
			d = ".example.com"
		}
		line := fmt.Sprintf("%s\tTRUE\t/\tTRUE\t2147483647\t%s\t%s\n", d, cookie.Name, cookie.Value)
		if _, err := file.WriteString(line); err != nil {
			_ = os.RemoveAll(dir)
			return "", fmt.Errorf("failed to write temporary cookie file: %w", err)
		}
	}

	return path, nil
}

// ── Linux cookie extraction via yt-dlp ────────────────────────────────────

// extractBrowserDataViaYTDLP dùng yt-dlp --cookies-from-browser thay vì kooky
// để tránh vấn đề GNOME Keyring/KWallet decrypt trên Linux.
func (m *CookieManager) extractBrowserDataViaYTDLP(
	ctx context.Context, browser string, targetHost string,
) (*BrowserExportData, error) {
	ytdlp := getResourcePath("yt-dlp")
	if ytdlp == "" {
		return nil, fmt.Errorf("yt-dlp not found")
	}

	extractionURL := buildExtractionURL(targetHost)

	tempDir, err := os.MkdirTemp("", "ytdown-cookies-*")
	if err != nil {
		return nil, fmt.Errorf("failed to create temp dir: %w", err)
	}
	defer os.RemoveAll(tempDir)
	tempCookieFile := filepath.Join(tempDir, "cookies.txt")

	cmdCtx, cancel := context.WithTimeout(ctx, 20*time.Second)
	defer cancel()

	// yt-dlp sẽ export cookies dù download fail → bỏ qua exit error
	_ = exec.CommandContext(cmdCtx, ytdlp,
		"--cookies-from-browser", browser,
		"--cookies", tempCookieFile,
		"--no-warnings",
		"--no-playlist",
		extractionURL,
	).Run()

	raw, err := os.ReadFile(tempCookieFile)
	if err != nil {
		return nil, fmt.Errorf("cookie file not written by yt-dlp: %w", err)
	}

	cookies, xhsSession := parseNetscapeCookieFileForDomain(string(raw), targetHost)
	userAgent := GetUserAgent(browser)

	result := &BrowserExportData{
		BrowserName: browser,
		UserAgent:   userAgent,
		WebSession:  xhsSession,
		Cookies:     cookies,
		Headers:     make(map[string]string),
		ExportTime:  time.Now(),
	}
	if xhsSession != "" {
		result.Headers["Cookie"] = "web_session=" + xhsSession
	}
	LogInfo("[Cookie] yt-dlp extracted %d cookies for %s from %s",
		len(cookies), targetHost, browser)
	return result, nil
}

// buildExtractionURL trả về URL phù hợp để yt-dlp extract cookies đúng domain
func buildExtractionURL(targetHost string) string {
	switch {
	case strings.Contains(targetHost, "xiaohongshu.com") ||
		strings.Contains(targetHost, "xhslink.com"):
		return "https://www.xiaohongshu.com/"
	case strings.Contains(targetHost, "instagram.com"):
		return "https://www.instagram.com/"
	case strings.Contains(targetHost, "tiktok.com"):
		return "https://www.tiktok.com/"
	case strings.Contains(targetHost, "twitter.com") ||
		strings.Contains(targetHost, "x.com"):
		return "https://x.com/"
	case strings.Contains(targetHost, "bilibili.com"):
		return "https://www.bilibili.com/"
	case strings.Contains(targetHost, "pixiv.net"):
		return "https://www.pixiv.net/"
	default:
		return "https://www.youtube.com/"
	}
}

// parseNetscapeCookieFileForDomain parse Netscape cookie file, filter theo domain
// và bắt web_session cho Xiaohongshu.
func parseNetscapeCookieFileForDomain(content, targetHost string) ([]parsedCookie, string) {
	var cookies []parsedCookie
	var xhsSession string

	// Build relevant domains
	var relevantDomains []string
	if strings.Contains(targetHost, "xiaohongshu.com") || strings.Contains(targetHost, "xhslink.com") {
		relevantDomains = []string{"xiaohongshu.com", "xhslink.com"}
	} else if strings.Contains(targetHost, "youtube.com") || strings.Contains(targetHost, "youtu.be") {
		relevantDomains = []string{"youtube.com"}
	} else if targetHost != "" {
		parts := strings.Split(targetHost, ".")
		if len(parts) >= 2 {
			relevantDomains = []string{parts[len(parts)-2] + "." + parts[len(parts)-1]}
		}
	}

	seen := make(map[string]bool)
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// Netscape format: domain \t domainFlag \t path \t secure \t expiry \t name \t value
		parts := strings.Split(line, "\t")
		if len(parts) < 7 {
			continue
		}
		domain, path, name, value := parts[0], parts[2], parts[5], parts[6]

		// Filter by domain
		if len(relevantDomains) > 0 {
			matched := false
			for _, rd := range relevantDomains {
				if strings.Contains(domain, rd) {
					matched = true
					break
				}
			}
			if !matched {
				continue
			}
		}

		// Dedup
		key := strings.TrimPrefix(domain, ".") + "|" + name
		if seen[key] {
			continue
		}
		seen[key] = true

		var expiry int64
		fmt.Sscanf(parts[4], "%d", &expiry)
		secure := strings.EqualFold(parts[3], "TRUE")

		cookies = append(cookies, parsedCookie{
			Domain:  domain,
			Path:    path,
			Name:    name,
			Value:   value,
			Secure:  secure,
			Expires: expiry,
		})

		if name == "web_session" &&
			(strings.Contains(domain, "xiaohongshu.com") || strings.Contains(domain, "xhslink.com")) {
			xhsSession = value
		}
	}
	return cookies, xhsSession
}
