// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPlaylist(arg1:string):Promise<Record<string, any>>;

export function GetDefaultSavePath():Promise<string>;

export function GetVideoTitle(arg1:string):Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function RetryDownload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StartBatchDownload(arg1:Array<string>,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StartDownload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ValidateURL(arg1:string):Promise<boolean>;
