// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPlaylist(arg1) {
  return window['go']['main']['App']['CheckPlaylist'](arg1);
}

export function GetDefaultSavePath() {
  return window['go']['main']['App']['GetDefaultSavePath']();
}

export function GetVideoTitle(arg1) {
  return window['go']['main']['App']['GetVideoTitle'](arg1);
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function RetryDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RetryDownload'](arg1, arg2, arg3, arg4);
}

export function StartBatchDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartBatchDownload'](arg1, arg2, arg3, arg4);
}

export function StartDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3, arg4);
}

export function ValidateURL(arg1) {
  return window['go']['main']['App']['ValidateURL'](arg1);
}
